export const products = [
    {
      id: 1,
      name: "100% Gold Standard Whey",
      price: 1490,
      stock: 9,
      description: "",
      category: "proteina",
      img: "https://res.cloudinary.com/dsorb9btj/image/upload/v1670884215/React%20App%20CoderHouse/image_qjggpz.png",
    },
    {
      id: 2,
      name: "Creatina Monohidratada",
      price: 550,
      stock: 16,
      description: "",
      category: "creatina",
      img: "https://res.cloudinary.com/dsorb9btj/image/upload/v1670884286/React%20App%20CoderHouse/image_oquzmo.png",
    },
    {
      id: 3,
      name: "Glutamina",
      price: 350,
      stock: 3,
      description: "",
      category: "glutamina",
      img: "https://res.cloudinary.com/dsorb9btj/image/upload/v1670884293/React%20App%20CoderHouse/image_ribrho.png",
    },
    {
      id: 4,
      name: "B-NOX Betancourt",
      price: 450,
      stock: 7,
      description: "",
      category: "pre-entreno",
      img: "https://res.cloudinary.com/dsorb9btj/image/upload/v1670884240/React%20App%20CoderHouse/image_v5uyh6.png",
    },
    {
      id: 5,
      name: "Shaker Smart Shake",
      price: 170,
      stock: 7,
      description: "",
      category: "accesorios",
      img: "https://res.cloudinary.com/dsorb9btj/image/upload/v1670884256/React%20App%20CoderHouse/image_ourlsg.png",
    },
    {
      id: 6,
      name: "Ostarine MK 2866",
      price: 790,
      stock: 7,
      description: "",
      category: "vitaminas",
      img: "https://res.cloudinary.com/dsorb9btj/image/upload/v1670884210/React%20App%20CoderHouse/image_p5iwhe.png",
    },
  ];
  